### ISSUE TITLE
Allow exclusion of network device(s)

### ISSUE THREAD

**Issue by kennethso168** [Jip-Hop/sedunlocksrv-pba#10]
As mentioned in #9 I intended to have a virtualized router on the server with SED-protected disk. I found that the PBA image will try to configure all network devices with dynamic IP addresses using DHCP, and the web server and SSH server will listen on all interfaces. That may not be desirable in my case as this will inadvertently expose the web server and SSH server to the Internet.

And I have [implemented exclusion of network device(s) as well in my fork](https://github.com/kennethso168/sedunlocksrv-pba/commit/3a0e2a82089c5d970f0a54e497f81af21817e6c0). Here is a screenshot of this in action in my Proxmox VM (`eth1` and `eth2` being excluded for DHCP broadcasting):
![image](https://github.com/Jip-Hop/sedunlocksrv-pba/assets/5262487/802fb560-40bf-4b3a-9669-98ab902d3664)

Would you like me to open a PR for this?

**Comment by Jip-Hop** [comment]
Yes please open a PR. Looks neat and already complete with updated Readme. 😄
