### ISSUE TITLE
Does this work with secure boot enabled?

### ISSUE THREAD

**Issue by ChubbyAnt** [Jip-Hop/sedunlocksrv-pba#2]
Does this work with secure boot enabled?

**Comment by Jip-Hop** [comment]
I don't know... Please let me know if you tried  🙂

**Comment by Jip-Hop** [comment]
Since this is a question and I don't know the answer I'm closings this issues. It can be reopened if someone tries and reports it's not working with secure boot.

**Comment by don-dolarson** [comment]
How can I properly test the Secure Boot? I've already flashed MBR shadow with this PBA build and set up sedutil from RESCUE64 in UEFI mode (CSM enabled), Secure Boot disabled, to a nicely working PBA.

Simply switch Secure Boot to enabled and try to boot the PBA and then let it chainload the UEFI operating system or do I need to set everything up from scratch in different mode?

**Comment by Jip-Hop** [comment]
I think it won't boot when you enable Secure Boot without additional configuration. But you can try or course. However I don't know what you have to do exactly to make this PBA work with Secure Boot.

**Comment by don-dolarson** [comment]
I'll test switch Secure Boot to enabled and boot as fast as I can. I just wanted to help and give an answer to this thread.

**Comment by Jip-Hop** [comment]
Much appreciated :) The OS I boot after unlocking the SED with the sedunlocksrv-pba, [TrueNAS SCALE, doesn't support Secure Boot (out of the box)](https://www.truenas.com/community/threads/enabling-secureboot-on-truenas-scale.109162/) so I have to disable it anyway.

**Comment by don-dolarson** [comment]
I should be able to test it in a couple of days when home. This time I'll boot an UEFI OpenWrt x86 Intel J4125 based router. Do the OS must support Secure Boot as well? I doubt OpenWrt does but need check it. However later this year I can test it on Ryzen 1700X B450 and Ryzen 2400G A320 UEFI based machines running Fedora/RHEL and an Arch distro.
