### ISSUE TITLE
Option to use other forks of sedutil

### ISSUE THREAD

**Issue by kennethso168** [Jip-Hop/sedunlocksrv-pba#8]
Many thanks for the great project!

I have been using [ChubbyAnt's fork of sedutil](https://github.com/ChubbyAnt/sedutil) for my own server for its use of SHA-512 password algorithm instead of SHA-1 and additional support for AMD systems.

I have figured out the way to swap Drive-Trust-Alliance's `sedutil-cli` binary with ChubbyAnt's. Please see [the relevant commit of my fork](https://github.com/kennethso168/sedunlocksrv-pba/commit/e5b860e25d197b1b6726a8b1833471c27128cd23)

I'm still thinking of a way to allow user to choose between the forks of sedutil used when running the build script. I'm leaning towards the use of environmental variables, e.g. `SEDUTIL_FORK="ChubbyAnt" ./build.sh` (the default being Drive-Trust-Alliance when the variable isn't defined).

Any ideas? If we agree on the way of implementation, I can modify the build script accordingly and prepare a PR.

**Comment by Jip-Hop** [comment]
Glad to hear the project is useful to you. 😄Your proposal to use an environment variable to override which sedutil fork to use sounds good! Looking forward to the pull request.

**Comment by kennethso168** [comment]
Thanks, I'll modify the script and do the PR when free.
